### ISSUE TITLE
HtmlProvider Tables parsing not working correctly when there's additional attributes

### ISSUE THREAD

**Issue by KoenigLear** [fsharp/FSharp.Data#1098]
The table in your data tests fails as soon you add attributes e.g. align, border etc.  
`<table` title="table" align="center" border="0" cellspacing="0" cellpadding="0">

By fails I mean that using the type provider html = typeA.load("html").Tables is empty.  It's expected that it would return a table.

**Comment by ovatsus** [comment]
@colinbull want to have a look?

**Comment by ElegantElephant44** [comment]
@KoenigLear Tables is empty because you adding cellspacing="0" cellpadding="0" and don't setting IncludeLayoutTables to true. This code inside HtmlRuntime.cs filter such tables 
`let tableElements = 
            if includeLayoutTables
            then tableElements
            else tableElements |> List.filter (fun (e, _) -> not (e.HasAttribute("cellspacing", "0") && e.HasAttribute("cellpadding", "0")))`
You can check without these attributes or set IncludeLayoutTables to true, everything should work.
