### ISSUE TITLE
Large post body causes erroneous 'Invalid URI: The Uri string is too long.' error 

### ISSUE THREAD

**Issue by f4hy** [fsharp/FSharp.Data#1104]
Hey again, 

A while back I posted an issue #1077 which found that `FSharp.Data.Http.Request` would fail if the body size was too large.

This issue is to report that again the same thing is happening but now for larger body values. The biggest problem is that the error message produced is incorrect as well. When a large body is passed in the error given is `'Invalid URI: The Uri string is too long.'` when I can demonstrate that running with the same URI and just changing the body causes the failure.

This is the same example code I posted in issue #1077 except increased the size of the second test case:
```
#r @"FSharp.Data.dll"
open FSharp.Data

let bodyString = seq {for i in 0..1000 -> "x\n"} |> String.concat ""
let body = FSharp.Data.FormValues([("input",bodyString)])
FSharp.Data.Http.Request(url="http://httpbin.org/post",httpMethod="POST",body=body)
//Works fine

let bodyString2 = seq {for i in 0..20000 -> "x\n"} |> String.concat ""
let body2 = FSharp.Data.FormValues([("input",bodyString2)])
FSharp.Data.Http.Request(url="http://httpbin.org/post",httpMethod="POST",body=body2)
//throws System.UriFormatException: Invalid URI: The Uri string is too long.
```

As you can see the URI should be the same in both cases.

**Comment by f4hy** [comment]
@baronfel I am not sure if the cause is exactly the same as last time you fixed this but seems like a very similar case.

**Comment by f4hy** [comment]
Could be related to #1082 but looks like we get different errors from the same root cause.

**Comment by baronfel** [comment]
Did some poking here earlier today and have a hypothesis for the failure:

When we prepare a form data payload for sending, we UrlEncode the [key and value](https://github.com/fsharp/FSharp.Data/blob/master/src/Net/Http.fs#L1595). The method that we're using to encode these parts throws a `UriFormatException` with the message you've seen because your string value exceeds a hard-coded limit of 32766 characters. This makes some kind of since because different servers/browsers have URL length limits.

But for FormData body encoding, we do not need this limit as you have found!

So we should replace our use of Uri.EscapeDataString for the key and value of the form data with something more correct.

I propose we use the mostly correct encoder in System.Net.WebUtility.UrlEncode and patch up the edge case it doesn't cover (notably it doesn't encode `+` as `%20` correctly) and then we should be good.

**Comment by f4hy** [comment]
I have tested #1112 locally and it fixes this issue. Thanks @panesofglass !
