### ISSUE TITLE
JsonProvider looks in incorrect path for the sample file in a referenced project

### ISSUE THREAD

**Issue by rabejens** [fsharp/FSharp.Data#1110]
When I reference a project that uses the `JsonProvider`, compiling it tries to reference the sample file from the current project, not the referenced one.

Steps to reproduce:

- Start a blank solution in VS 2015
- Add a F# library
- Add a JSON file to this library, call it `test.json` and add the following:
```json
{
  "foo": "bar"
}
```
- Add a source file with the following:
```fsharp
namespace FSDataReferenceProblem

open FSharp.Data

type Foo = JsonProvider<"test.json">
```
- Add a console application, reference the library, and add another JSON file, call it something different than `test.json`, e.g., `foo.json`, and set `Copy to Output Directory` to `Copy Always`:
```json
{
  "foo": "quux"
}
```
- In Program.fs, in the main function, add:
```fsharp
let foo = FSDataReferenceProblem.Foo.Load("foo.json")
printfn "foo is: %s" foo.Foo
```

Expected: Output `foo is: quux`

What I get: The main program doesn't compile, instead I get the error `Cannot read sample JSON from 'test.json': Could not find file 'C:\Some\Where\TheSolution\MainProgram\test.json`

So, it looks for the sample file in the project that references the library, not in the library directory.

Is this a bug, is this intended, and if the latter applies, is there another way other than copying the sample file to each referencing project?

**Comment by tpetricek** [comment]
This is an expected behaviour - copying [answer from StackOverflow](https://stackoverflow.com/questions/47632912/f-type-provider-looks-for-sample-file-in-referencing-project-not-referenced-pr/47634855) about this:

---

When you use an F# Data type provider in a library and you reference the library, the compiler will try to access the sample - this is because the types are erased and are recreated each time they are used. (They are also lazily generated, and so they are generated on the fly as they are being used, so this is the only option.)

If you can copy the files with your library, that's probably the best option, but we tried to address this issue - you can embed the sample as a resource and tell the type provider to look for a resource first. See [Using JSON provider in a library](http://fsharp.github.io/FSharp.Data/library/JsonProvider.html) in the F# Data docs:

    type WB = JsonProvider<"../data/WorldBank.json", 
      EmbeddedResource="MyLib, worldbank.json">

This is used, for example, in the [F# Data Toolbox](http://fsprojects.github.io/FSharp.Data.Toolbox/) library. Alas getting this to work well is a bit fiddly.
