### ISSUE TITLE
3.0.0-beta4: XmlProvider ignores attribute default in schema

### ISSUE THREAD

**Issue by unixwitch** [fsharp/FSharp.Data#1189]
hello,

the new XML Schema support in 3.0.0 is really nice, thanks for integrating that.  however, i think i've found a small bug: when the schema specifies a default attribute value, the provider ignores it when parsing a document; i.e., if the attribute is not present in the element, it returns None instead of the default value.

minimal test case:

```fsharp
open FSharp.Data

type DefaultTest = XmlProvider<Schema="""
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="test">
        <xs:complexType>
            <xs:attribute name="myattr" use="optional" type="xs:string" default="a default value"/>
        </xs:complexType>
    </xs:element>
</xs:schema>""">

[<EntryPoint>]
let main argv =
    printfn "%A" (DefaultTest.Parse("""<test myattr="a value"/>""").Myattr)
    printfn "%A" (DefaultTest.Parse("""<test />""").Myattr)
    0
```

actual output:

```
Some "a value"
<null>
```

expected output:

```
Some "a value"
Some "a default value"
```

(tested with FSharp.Data 3.0.0-beta4, FSharp.Core 4.5.2, .NET Framework 4.7.1 in VS2017.)

**Comment by giacomociti** [comment]
Interesting issue. Honestly I was not even aware of default values, and investigating this I learned not only about them, but also that `XDocument` has a `Validate` extension method that can do the job for us  (thanks to the `addSchemaInfo` flag):

    open System.Xml
    open System.Xml.Schema

    let parseSchema xsdText =    
        let schemaSet = XmlSchemaSet() 
        use reader = XmlReader.Create(new System.IO.StringReader(xsdText))
        schemaSet.Add(null, reader) |> ignore
        schemaSet.Compile()
        schemaSet


    [<Literal>]
    let AttributeWithDefault = """
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:element name="test">
            <xs:complexType>
                <xs:attribute name="myattr" use="optional" type="xs:string" default="a default value"/>
            </xs:complexType>
        </xs:element>
    </xs:schema>"""

    let doc = XDocument.Parse """<test />"""
    let xsd = parseSchema AttributeWithDefault

    doc.Root.Attribute(XName.Get "myattr") |> printfn "%A" // <null>
    doc.Validate(xsd, validationEventHandler = null, addSchemaInfo = true)
    doc.Root.Attribute(XName.Get "myattr") |> printfn "%A" // "a default value"

    type DefaultTest = XmlProvider<Schema=AttributeWithDefault>

    printfn "%A" (DefaultTest.Test(doc.Root).Myattr)
    // Some "a default value"


As you can see the validation method set default values as a side effect.

I admit it's a bit annoying having to parse the xsd, validate the document and then create an instance from the already parsed and validated document instead of calling the `Load` or `Parse` method of the provided type.

Most of this could be somehow included in the type provider, but in the meantime I hope the snippet above can help.
