### ISSUE TITLE
HtmlProvider cannot parse Wikipedia articles

### ISSUE THREAD

**Issue by malayantiger** [fsharp/FSharp.Data#1299]
Parsing Wikipedia articles with HtmlProvider (FSharp.Data v3.3.3) seems to be broken, reproduction:
```
let [<Literal>] url = "https://en.wikipedia.org/wiki/Special:Random"
type Foo = HtmlProvider<url>

let lists = Foo.Load(url).Lists
let languages = lists.Languages
```
`lists.Languages` fails with:
```
at Microsoft.FSharp.Collections.MapTreeModule.find[TKey,TValue](IComparer`1 comparer, TKey k, MapTree`2 m) in E:\A\_work\130\s\src\fsharp\FSharp.Core\map.fs:line 155
   at FSharp.Data.Runtime.BaseTypes.HtmlList`1.Create(Func`2 rowConverter, HtmlDocument doc, String id)
```

Inspecting html returned by `lists` shows:
```
<!DOCTYPE html>
<html lang="en">
  <meta charset="utf-8" /><title>Browser Connection Security Issues</title><style>
...
```

which seems to be this page: https://en.wikipedia.org/sec-warning

> We are removing support for insecure TLS protocol versions, specifically TLSv1.0 and TLSv1.1, which your browser software relies on to connect to our sites. This is usually caused by outdated browsers, or older Android smartphones. Or it could be interference from corporate or personal "Web Security" software, which actually downgrades connection security.

Parsing them in IntelliSense seems to work though.

**Comment by dsyme** [comment]
Anyone know the fix for this (and am surprised it's not caught by our testing...)?

**Comment by baronfel** [comment]
What version of .Net are you running on, @malayantiger?  Versions less than .Net Framework 4.7 use very old TLS settings by default, but you can try working around that by setting it manually as shown in [this stackoverflow answer](https://stackoverflow.com/a/53056328/433393).

@dsyme in the longer term we could be better net-citizens by moving to HttpClient instead of HttpWebRequest as the underlying driver in this library, as it has more modern defaults around this sort of thing, as well as plugging in to broader overall .net trends like using HttpMessageHandlers to pool clients, handle retries, etc.

**Comment by malayantiger** [comment]
Upgrading .Net from 4.5.2 to 4.7.2 fixed the issue. Thanks.

**Comment by dsyme** [comment]
Thanks all!
