### ISSUE TITLE
JsonProvider provided types with mutable properties

### ISSUE THREAD

**Issue by panesofglass** [fsharp/FSharp.Data#178]
Does the `JsonProvider` currently provide types with mutable properties? I didn't see anything in the docs or the source that indicated this was currently possible.

What would it take to make this change?

Is this change within the purview of the FSharp.Data project?

**Comment by dzmitry-lahoda** [comment]
I do not see mutable properties after `JsonProvider` generated me the type. Nor do I see lenses generated. Nor do I see option to generate mutable object. 

I followed several hops from this issues, but did not see it was done at all. 

Could we reopen issue? My use case using JSON as template I want to change some values and send updated.

Thanks

**Comment by dzmitry-lahoda** [comment]
https://github.com/fsharp/FSharp.Data/issues/914

**Comment by dzmitry-lahoda** [comment]
I want monkey coding with mutable generator https://github.com/dzmitry-lahoda/awesome-fsharp-projectional-coding

**Comment by jkone27** [comment]
I have some stuff to try out guys, I made the package yesterday in pre-release, the implementation is probably awful in terms of performance or reliability, but I have some tests, and I am totally open for changes :) . 
[FSharp.Data.Mutator](https://github.com/jkone27/FSharp.Data.Mutator)
I am writing a small medium article about it, I have been using it in some projects already, so decided to formalise it in a library. Maybe I could rename some implementations (e.g. With instead of Change, to make it more FSharpish as in copy mutation)
@dzmitry-lahoda let me know what you think 👍 , is in nuget preview

**Comment by jkone27** [comment]
i am trying to play around with this, could this be supported somehow as an optional parameter to the type provider?

but i dont know exactly how to map the setter :) probably the Dictionary string, obj will explode at runtime... 

IJsonDocument and the underlying JsonValue are immutable, unless is there any other way?

jsonGenerator.fs

```fsharp
              //TODO: pass from type provider constructor parameter
              let generateSetters = true

              //TODO: somehow allow mutation of underlying IJsonDocument.JsonValue
              let providedProperty =
                if generateSetters then
                  let setter (args: Quotations.Expr list) = 
                    let replacement = getter([ args.[1] ]) 
                    <@@ ((%%args.[0]:obj) :?> Dictionary<string,obj>).[propName] <- replacement @@>

                  ProvidedProperty(name, convertedType, getterCode = getter, setterCode = setter)
                else
                  ProvidedProperty(name, convertedType, getterCode = getter)
              
```
