### ISSUE TITLE
Pipe delimited csv with end-of-line pipe

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsharp/FSharp.Data#830]
I have a weird case of pipe delimited csv where each line ends with closing pipe

Name|Company |Email|Password
Johnson|ABC|johnson@abc.com|12345i|
Yoda|XYZ|yoda@xyz.com|98123j|

I get an error

Error	1	The type provider 'ProviderImplementation.CsvProvider' reported an error: Couldn't parse row 1 according to schema: Expected 4 columns, got 5

**Comment by tpetricek** [comment]
I'm not too surprised by this - it behaves this way, because the first line has just 4 columns and the next lines have 5 columns (with empty value for the last column).

I think it would be quite reasonable to allow additional separator at the end of a row, provided that there is nothing after it. This would be just a matter of changing [the check here](https://github.com/fsharp/FSharp.Data/blob/master/src/Csv/CsvRuntime.fs#L177), because I think all later code will just ignore the additional value. 

It is a bit ad-hoc hack, but something like this should probably do the trick:

    if untypedRow.Length <> numberOfColumns || 
      (untypedRow.Length = numberOfColumns + 1 && 
      String.IsNullOrEmpty(untypedRow.[untypedRow.Length-1])) then ...

Would you mind sending a pull request that adds this? (Together with a test for this and perhaps a test making sure that if you have some content after the separator (or more separators) at the end, then it still fails...)

If the change breaks some existing tests, then we can revisit them and see if this is actually problematic or not - it sounds safe enough to me.
