### ISSUE TITLE
Response stream in raised WebException is closed

### ISSUE THREAD

**Issue by rotmoset** [fsharp/FSharp.Data#835]
When the Http module catches a WebException during a http request it reads the response body from the exception's response stream using a StreamReader which is then disposed, thus closing the response stream. 

This means that clients that catches the reraised exception later and tries to access the response will find themselves with a closed stream and no way to access the response body except for digging it out of the exception message.

Changing the "use" bindings in the augmentWebExceptionsWithDetails function to "let" bindings leaves the stream open for clients, but I'm not sure if this is safe / sane.

**Comment by ovatsus** [comment]
I don't think leaving the stream open is a good idea. This behavior is by design, so that when you use these methods on FSI you can see the error messages straight away, it's very useful. If you need to deal with the response stream manually in case of errors, I suggest you use HttpWebRequest directly, instead of using FSharp.Data's HTTP module

**Comment by ovatsus** [comment]
You can also try using https://github.com/relentless/Http.fs instead which I don't think does this
