### ISSUE TITLE
JsonProvider trims property names

### ISSUE THREAD

**Issue by CSharpFan** [fsharp/FSharp.Data#891]
Consider the following piece of code:

```
open FSharp.Data


type Test = JsonProvider<"test.json">

[<EntryPoint>]
let main argv = 

    let loaded = Test.Load "test.json"

    let result = loaded.A234 // Where's my '1'?
    // let result = loaded.A1234 // this one doesn't compile

    printfn "%s" result
    
    0 
```

And `test.json`:

```
{ "A1234": "Test" } 
```

It seems that `A1234` is exposed as `A234`. 

Also, it fails to launch because it can't read from the file (no reference to `A234` in the JSON).

A full working, well, non-working ;-) example can be found here: https://github.com/CSharpFan/weird-json-type-generation

**Comment by xenocons** [comment]
Hello, I believe this is caused by UTF8 byte order marking, (see https://en.wikipedia.org/wiki/Byte_order_mark), your data that you posted within your git has the following: "EF BB BF 7B 20 22 41 31 32 33 34 22 3A 20 22 54 65 73 74 22 20 7D", notice the EF BB BF at the start). I suggest a workaround of the following:
```
let loaded = Test.Parse (IO.File.ReadAllText "test.json")
```

**Comment by ovatsus** [comment]
Marked as duplicate, a pull request to add an encoding optional parameter would be welcomed
