### ISSUE TITLE
Type Providers should Handle Missing Values by Default

### ISSUE THREAD

**Issue by drcrook1** [fsharp/FSharp.Data#927]
This is just a nice to have, not immediate, but would just generally be nice to have.

type m311C = CsvProvider<"C:\data\Miami_311.csv">
let m311 = m311C.Load("C:\data\Miami_311.csv")

m311.Rows |> Seq.length

crashes, then you have to go do this:

type m311C = CsvProvider<"C:\\data\\Miami_311.csv",
                            AssumeMissingValues=true>
let m311 = m311C.Load("C:\\data\\Miami_311.csv")

m311.Rows |> Seq.length

**Comment by tpetricek** [comment]
Can you share the data? It should not crash - the idea is that if your sample contains missing values, the CSV provider will infer column type as e.g. `option<int>`, but if the sample does _not_ contain missing values, then we can give you e.g. `int` directly...

**Comment by drcrook1** [comment]
Using miami service requests data found here: https://opendata.miamidade.gov/311/311-Service-Requests-Miami-Dade-County/dj6j-qg5t

**Comment by ovatsus** [comment]
See http://fsharp.github.io/FSharp.Data/reference/fsharp-data-csvprovider.html, by default CsvProvider only looks at first 1000 rows for inference, so if the first missing value is on a row after that, it will not detect it, and that's why we have that AssumeMissingValues param. That CSV file is very big, so that's probably what's happening. However, I don't think we should make that the default: it would generate a worst looking API in most cases, where it's not needed, and it would break compatibility in a big way with older versions of F# Data
