### ISSUE TITLE
Stream response API

### ISSUE THREAD

**Issue by et1975** [fsharp/FSharp.Data#940]
Just starting to look at using the Http API and have several concerns/questions:
- Does not [copying of the stream](https://github.com/fsharp/FSharp.Data/blob/f815de5e8108bb7de25dde75135707719afd8e09/src/Net/Http.fs#L878) defeat the purpose of streaming?
- Does not [returning a stream](https://github.com/fsharp/FSharp.Data/blob/f815de5e8108bb7de25dde75135707719afd8e09/src/Net/Http.fs#L885) leave me with responsibility if cleaning it up?

I'd propose:
- a wrapping stream, that doesn't read anything unless asked to
- a continuation argument that accepts the stream, which would allow the API implementation to dispose of the stream once the continuation returns/throws.

**Comment by ovatsus** [comment]
That stream needs to be always read to be decompressed, we used to do it more lazily but it caused a bunch of problems. These are supposed to be simple helpers for simplifying doing http calls, when you need more flexibility you should use the underlying libs instead.
You also don't need to cleanup because it's a memory stream, that's one of the reasons it's copied
