### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#943]

**Comment by coolya** [comment]
I was thinking about picking this on up, but while looking through the code I noticed there are already a bunch of `#ifdef`s that seems to make it compile. Were there other issues? I haven't run any tests so far.

**Comment by dsyme** [comment]
So... it turns out you can already use the FSharp.Data type provider when doing .NET Core programming through the workaround described here:

https://github.com/Microsoft/visualfsharp/issues/3303#issuecomment-312966306

(Aside: There is one warning which should be considered:
```
C:\GitHub\misc\tpapp2\tpapp2.fsproj : warning NU1701: Package 'FSharp.Data 2.3.3' was restored using '.NETFramework,Version=v4.6.1' instead the project target framework '.NETCoreApp,Version=v2.0'. This may cause compatibility problems.
```
However I believe that could go away by publishing the right FSharp.Data.dll for .NET Standard 2.0, which we can do in due course.)

**Comment by ovatsus** [comment]
Done in 3.0
