### ISSUE TITLE
JsonParserProperties.Parsing stringified JsonValue returns the same JsonValue failing

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#977]
Fails on CI and locally when running through FAKE, but when running inside the VS test runner works fine

**Comment by nejcskofic** [comment]
It seems that the problem is due to console test runner utilising multiple  threads and that '_fixtureSetup_' method runs on different thread than actual test. Since generator registration is done [per thread](https://github.com/fscheck/FsCheck/blob/fb0f915fabe985f04ee1a6fef915289b7ae50cad/src/FsCheck/Arbitrary.fs#L157), unit test does not have custom generator for '_JsonValue_' registered and defaults to reflection based one which generates  primitive such as '_JsonValue.Null_' and that causes test to fail.

Workaround would be to register generator directly in test case:
```F#
let  ``Parsing stringified JsonValue returns the same JsonValue`` () =
    Arb.register<Generators>() |> ignore

    let parseStringified (json: JsonValue) =
        json.ToString(JsonSaveOptions.DisableFormatting)
        |> JsonValue.Parse = json

    Check.One ({Config.QuickThrowOnFailure with MaxTest = 1000},
               parseStringified)
```

**Comment by ovatsus** [comment]
Thanks @nejcskofic, could you please send a PR with that change?

**Comment by nejcskofic** [comment]
Sent PR #1035.

**Comment by ovatsus** [comment]
Thanks!
